"""schema initial

Revision ID: 001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendrier',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('service_id', 'date')
    )
    with op.batch_alter_table('calendrier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendrier_date'), ['date'], unique=False)

    op.create_table('evenement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lieu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('departement', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('gare_proche_id', sa.Integer(), nullable=True),
    sa.Column('distance_gare_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gare_proche_id'], ['lieu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lieu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lieu_departement'), ['departement'], unique=False)
        batch_op.create_index(batch_op.f('ix_lieu_gare_proche_id'), ['gare_proche_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lieu_type'), ['type'], unique=False)

    op.create_table('reseau',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arret',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reseau_id', sa.String(), nullable=False),
    sa.Column('lieu_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieu.id'], ),
    sa.ForeignKeyConstraint(['reseau_id'], ['reseau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arret', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arret_lieu_id'), ['lieu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arret_reseau_id'), ['reseau_id'], unique=False)

    op.create_table('evenement_lieu',
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('lieu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieu.id'], ),
    sa.PrimaryKeyConstraint('evenement_id', 'lieu_id')
    )
    with op.batch_alter_table('evenement_lieu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evenement_lieu_lieu_id'), ['lieu_id'], unique=False)

    op.create_table('evenement_periode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evenement_periode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evenement_periode_date_debut'), ['date_debut'], unique=False)
        batch_op.create_index(batch_op.f('ix_evenement_periode_evenement_id'), ['evenement_id'], unique=False)

    op.create_table('gare',
    sa.Column('lieu_id', sa.Integer(), nullable=False),
    sa.Column('code_uic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieu.id'], ),
    sa.PrimaryKeyConstraint('lieu_id'),
    sa.UniqueConstraint('code_uic')
    )
    op.create_table('ligne',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reseau_id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('type_transport', sa.String(), nullable=True),
    sa.Column('couleur', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reseau_id'], ['reseau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ligne', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ligne_reseau_id'), ['reseau_id'], unique=False)

    op.create_table('station_velo',
    sa.Column('lieu_id', sa.Integer(), nullable=False),
    sa.Column('reseau', sa.String(), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieu.id'], ),
    sa.PrimaryKeyConstraint('lieu_id')
    )
    op.create_table('circulation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ligne_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ligne_id'], ['ligne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circulation_ligne_id'), ['ligne_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circulation_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_circulation_service_id'), ['service_id'], unique=False)

    op.create_table('gare_horaire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gare_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('heure_ouverture', sa.Time(), nullable=True),
    sa.Column('heure_fermeture', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['gare_id'], ['gare.lieu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gare_horaire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gare_horaire_gare_id'), ['gare_id'], unique=False)

    op.create_table('passage',
    sa.Column('circulation_id', sa.String(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('arret_id', sa.String(), nullable=False),
    sa.Column('heure_arrivee', sa.Integer(), nullable=True),
    sa.Column('heure_depart', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arret_id'], ['arret.id'], ),
    sa.ForeignKeyConstraint(['circulation_id'], ['circulation.id'], ),
    sa.PrimaryKeyConstraint('circulation_id', 'ordre')
    )
    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passage_arret_id'), ['arret_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passage_arret_id'))

    op.drop_table('passage')
    with op.batch_alter_table('gare_horaire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gare_horaire_gare_id'))

    op.drop_table('gare_horaire')
    with op.batch_alter_table('circulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circulation_service_id'))
        batch_op.drop_index(batch_op.f('ix_circulation_numero'))
        batch_op.drop_index(batch_op.f('ix_circulation_ligne_id'))

    op.drop_table('circulation')
    op.drop_table('station_velo')
    with op.batch_alter_table('ligne', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligne_reseau_id'))

    op.drop_table('ligne')
    op.drop_table('gare')
    with op.batch_alter_table('evenement_periode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evenement_periode_evenement_id'))
        batch_op.drop_index(batch_op.f('ix_evenement_periode_date_debut'))

    op.drop_table('evenement_periode')
    with op.batch_alter_table('evenement_lieu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evenement_lieu_lieu_id'))

    op.drop_table('evenement_lieu')
    with op.batch_alter_table('arret', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arret_reseau_id'))
        batch_op.drop_index(batch_op.f('ix_arret_lieu_id'))

    op.drop_table('arret')
    op.drop_table('reseau')
    with op.batch_alter_table('lieu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lieu_type'))
        batch_op.drop_index(batch_op.f('ix_lieu_gare_proche_id'))
        batch_op.drop_index(batch_op.f('ix_lieu_departement'))

    op.drop_table('lieu')
    op.drop_table('evenement')
    with op.batch_alter_table('calendrier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendrier_date'))

    op.drop_table('calendrier')
    # ### end Alembic commands ###
